site_name: LogDir
site_author: Bryon Tjanaka
copyright: "Copyright &copy; 2020 Bryon Tjanaka"
site_url: https://logdir.btjanaka.net
repo_url: https://github.com/btjanaka/logdir
repo_name: btjanaka/logdir
nav:
  - Home: index.md
  - API: api.md
  - Contributing: contributing.md
plugins:
  - search
  - mkdocstrings:
      watch:
        - logdir
      handlers:
        python:
          rendering:
            show_object_full_path: True
            show_root_toc_entry: False
theme:
  name: material
  palette:
    accent: deep orange
  icon:
    logo: material/folder
  favicon: img/favicon.svg
extra_css:
  - css/mkdocstrings.css
  - css/custom.css
